[project]
name = "waitrose-scraper"
version = "0.1.0"
description = "FastAPI + Crawl4AI scraper"
requires-python = ">=3.10"

dependencies = [
    "fastapi",
    "uvicorn[standard]",
    "crawl4ai",
    "python-dotenv",
    "pydantic",
    "playwright",
]
